services:
  modx_client:
    image: public.ecr.aws/z4n6o0v4/modx/client:latest
    container_name: modx_client
    expose:
      - 4173
    networks:
      - caddy_net

  modx_server:
    image: public.ecr.aws/z4n6o0v4/modx/server:latest
    container_name: modx_server
    expose:
      - 8080
    environment:
      - INFISICAL_TOKEN=$INFISICAL_TOKEN  
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - caddy_net

  postgres:
    image: postgres:14-alpine
    container_name: modx_postgres
    user: postgres
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - caddy_net

volumes:
  postgres_data:
networks:
  caddy_net:
    external: true
