services:
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    container_name: caddy_proxy
    # ports for Caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      # Mount the host Caddyfile
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    # Connect the Caddy container caddy_net
    networks:
      - caddy_net

  server:
    image: modx
    expose:
      - 8080
    environment:
      - PORT=8080
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - caddy_net

  postgres:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=junepoon
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ModX
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - caddy_net

volumes:
  caddy_data:
  caddy_config:
networks:
  caddy_net:
